### ISSUE TITLE
An installation issue

### ISSUE THREAD

**Issue by DISCORDzzz** [Jiayuan-Gu/hab-mobile-manipulation#3]
- hi, I create my conda env as  required in instructions, which is python=3.7. when I tried to install habitat-sim, I got several issues. One of them  is that  when running  `python setup.py install --bullet --headless` , there is issue said :

CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "setup.py", line 472, in <module>
    include_package_data=True,
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 262, in run
    self.build_extension(ext)
  File "setup.py", line 365, in build_extension
    cwd=self.build_temp,
  File "/home/yvhongfei/anaconda3/envs/hab/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/yvhongfei/Try/hab-mobile-manipulation/habitat-sim/build/lib.linux-x86_64-cpython-37/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/yvhongfei/anaconda3/envs/hab/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DREL_BUILD_RPATH=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=OFF', '-DTARGET_HEADLESS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=ON', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF', '-DBUILD_BASIS_COMPRESSOR=OFF', '/home/yvhongfei/Try/hab-mobile-manipulation/habitat-sim/src']' returned non-zero exit status 1.

what should I do?

**Comment by Jiayuan-Gu** [comment]
Hi, I followed the instruction I provided in the README to install the requirements, and successfully ran the example. From your error log, the error seems to be relevant to CMake. Can you create a clean environment to test again? Or you can share me with a docker image that can reproduce this error, otherwise it is hard for me to provide suggestions. Thanks.


The installation instruction:

```bash
# Ensure the latest submodules
git submodule update --init --recursive
# Create a conda env
conda create -n hab-mm python=3.7
# Activate the conda env
conda activate hab-mm
# Install habitat-sim from source
conda install cmake=3.14.0 patchelf ninja
cd habitat-sim && pip install -r requirements.txt && python setup.py install --bullet --headless && cd ..
# Install habitat-lab
cd habitat-lab && pip install -r requirements.txt && python setup.py develop && cd ..
# Install requirements
pip install -r requirements.txt
# Install habitat manipulation
python setup.py develop
# Post-installation
echo "export MAGNUM_LOG=quiet HABITAT_SIM_LOG=quiet" >> ~/.bashrc
```

**Comment by LZHLilE** [comment]
@DISCORDzzz Hi, I have encountered the same issue recently. Have you fixed it? 
I'd appreciate it if you could help me.
