### ISSUE TITLE
Cannot load URDF file

### ISSUE THREAD

**Issue by LZHLilE** [Jiayuan-Gu/hab-mobile-manipulation#7]
Hi, I'm using your dokcer image to create a container and steup the habitat-lab and hab-mobile-manipulation. And everything is ready, including data and episodes. However, there comes an issue about the URDF file when I tried to run a play-demo.
`(base) ubuntu@949561b4793d:~/work/hab-mobile-manipulation$ python habitat_extensions/tasks/rearrange/play.py
pybullet build time: Sep 22 2020 00:55:20
Neither `ifconfig` (`ifconfig -a`) nor `ip` (`ip address show`) commands are available, listing network interfaces is likely to fail
Loaded /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/play.yaml
Merging /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/base.yaml into /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/play.yaml
Loaded /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/base.yaml
Merging /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/__base__.py into /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/base.yaml
Loaded /home/ubuntu/work/hab-mobile-manipulation/configs/rearrange/tasks/__base__.py
2023-11-09 11:16:10,090 Initializing dataset RearrangeDataset-v0
2023-11-09 11:16:12,117 initializing sim RearrangeSim-v0
b3Warning[examples/Importers/ImportURDFDemo/UrdfFindMeshFile.h,102]:
habitat_extensions/assets/robots/hab_fetch/robots/hab_fetch_arm.urdf:12: cannot find '../meshes/base_link.dae' in any directory in urdf path
b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
Could not parse visual element for Link:b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
base_linkb3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
failed to parse linkTraceback (most recent call last):
  File "habitat_extensions/tasks/rearrange/play.py", line 269, in <module>
    main()
  File "habitat_extensions/tasks/rearrange/play.py", line 219, in main
    env: RearrangeRLEnv = env_cls(config)
  File "/home/ubuntu/work/hab-mobile-manipulation/habitat_extensions/tasks/rearrange/env.py", line 31, in __init__
    super().__init__(self._core_env_config, dataset=dataset)
  File "/home/ubuntu/work/hab-mobile-manipulation/habitat-lab/habitat/core/env.py", line 377, in __init__
    self._env = Env(config, dataset)
  File "/home/ubuntu/work/hab-mobile-manipulation/habitat-lab/habitat/core/env.py", line 108, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/home/ubuntu/work/hab-mobile-manipulation/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/ubuntu/work/hab-mobile-manipulation/habitat_extensions/tasks/rearrange/sim.py", line 93, in __init__
    ARM_URDF, joint_indices=[0, 1, 2, 3, 4, 5, 6], ee_link_idx=7
  File "/home/ubuntu/work/hab-mobile-manipulation/habitat_extensions/robots/pybullet_utils.py", line 45, in __init__
    physicsClientId=self.client_id,
pybullet.error: Cannot load URDF file.`
I'd appreciate it if you could help me.
Best,
Zihao Luan

**Comment by LZHLilE** [comment]
I'm using a headless remote server. Is there any problem with the headless mode?

**Comment by Jiayuan-Gu** [comment]
Sorry for the late reply. I think the error is caused from some missing asset: 
```
b3Warning[examples/Importers/ImportURDFDemo/UrdfFindMeshFile.h,102]:
habitat_extensions/assets/robots/hab_fetch/robots/hab_fetch_arm.urdf:12: cannot find '../meshes/base_link.dae' in any directory in urdf path
b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
Could not parse visual element for Link:b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
base_linkb3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
failed to parse linkTraceback (most recent call last):
```
